### ISSUE TITLE
Initializing submodules in core results in 'unable to check out'

### ISSUE THREAD

**Issue by MaiaBlanco** [Skielex/thinqpbo#1]
The specific error I am seeing is this:
`Unable to checkout 'ea0ce275be9a9964b682c65bfa6b006984c829a8' in submodule path 'thinqpbo/src/core'`

My configuration is Windows Subsystem for Linux, running Python 3.4. I have Cython installed.

Is it possible that you have a commit for that submodule in src/core that has not made it up to GitHub?

**Comment by Skielex** [comment]
Sorry about that. New to submodules. Should be pushed now :)
