### ISSUE TITLE
Install attempt via pip or using setup.py results in missing file error

### ISSUE THREAD

**Issue by MarkBlanco** [Skielex/thinqpbo#2]
Attempting to install using 'pip install thinqpbo' results in the following error:
`'thinqpbo/src/_qpbo.pyx' doesn't match any files`

As in the other issue I've made regarding pulling submodules from GitHub, my setup is Python 3.4 running on Windows Subsystem for Linux, on Windows 10.

Please let me know if you need additional information. Thanks.

**Comment by Skielex** [comment]
I assume it's an issue with relative paths. I've only tested it on Windows 10. Works fine for me. I'll look into it...

**Comment by MarkBlanco** [comment]
Seems like this may be the issue. I successfully installed it using pip in an anaconda virtual environment with python 3.6.6, native to Windows 10 rather than in WSL (Windows Subsystem for Linux).

That said, if you are able to resolve the issue with relative paths it would be much appreciated! Thanks for your responses.

**Comment by MarkBlanco** [comment]
Hi, I've embedded my error log (stdout + stderr) from my latest attempt at doing "python setup.py install" using python 3.4 on WSL. Hopefully it's useful:

>running install
/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /mnt/c/Users/markb/.../thinqpbo/thinqpbo/src/_qpbo.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
Error compiling Cython file:
distutils: language = c++
from _QPBO cimport QPBO, EdgeId
thinqpbo/src/_qpbo.pyx:3:0: '_QPBO.pxd' not found
Error compiling Cython file:
distutils: language = c++
from _QPBO cimport QPBO, EdgeId
thinqpbo/src/_qpbo.pyx:3:0: '_QPBO/QPBO.pxd' not found
Error compiling Cython file:
distutils: language = c++
from _QPBO cimport QPBO, EdgeId
thinqpbo/src/_qpbo.pyx:3:0: '_QPBO/EdgeId.pxd' not found
Error compiling Cython file:
from _QPBO cimport QPBO, EdgeId
cdef public class QPBOInt[object PyObject_QPBOInt, type QPBOInt]:
    cdef QPBO[int]* c_qpbo
thinqpbo/src/_qpbo.pyx:7:9: 'QPBO' is not a type identifier
Error compiling Cython file:
cdef public class QPBOInt[object PyObject_QPBOInt, type QPBOInt]:
    cdef QPBO[int]* c_qpbo
    def __cinit__(self, int node_num_max=0, EdgeId edge_num_max=0):
thinqpbo/src/_qpbo.pyx:9:44: 'EdgeId' is not a type identifier
Error compiling Cython file:
        """
        return self.c_qpbo.Improve()
cdef public class QPBOFloat[object PyObject_QPBOFloat, type QPBOFloat]:
    cdef QPBO[float]* c_qpbo
thinqpbo/src/_qpbo.pyx:182:9: 'QPBO' is not a type identifier
Error compiling Cython file:
cdef public class QPBOFloat[object PyObject_QPBOFloat, type QPBOFloat]:
    cdef QPBO[float]* c_qpbo
    def __cinit__(self, int node_num_max=0, EdgeId edge_num_max=0):
thinqpbo/src/_qpbo.pyx:184:44: 'EdgeId' is not a type identifier
Error compiling Cython file:
        """
        return self.c_qpbo.Improve()
cdef public class QPBODouble[object PyObject_QPBODouble, type QPBODouble]:
    cdef QPBO[double]* c_qpbo
thinqpbo/src/_qpbo.pyx:357:9: 'QPBO' is not a type identifier
Error compiling Cython file:
cdef public class QPBODouble[object PyObject_QPBODouble, type QPBODouble]:
    cdef QPBO[double]* c_qpbo
    def __cinit__(self, int node_num_max=0, EdgeId edge_num_max=0):
thinqpbo/src/_qpbo.pyx:359:44: 'EdgeId' is not a type identifier
Error compiling Cython file:
        Similarly for edges.
        2. If Probe() is used with option=1 or option=2, then it is advisable to specify
        a larger value of edge_num_max (e.g. twice the number of edges in the original energy).
        """
        self.c_qpbo = new QPBO[int](node_num_max, edge_num_max)
thinqpbo/src/_qpbo.pyx:27:26: 'QPBO' is not a type identifier
Error compiling Cython file:
        Similarly for edges.
        2. If Probe() is used with option=1 or option=2, then it is advisable to specify
        a larger value of edge_num_max (e.g. twice the number of edges in the original energy).
        """
        self.c_qpbo = new QPBO[int](node_num_max, edge_num_max)
thinqpbo/src/_qpbo.pyx:27:26: new operator can only be applied to a C++ class
Error compiling Cython file:
        self.c_qpbo = new QPBO[int](node_num_max, edge_num_max)
    def __dealloc__(self):
        """Destructor
        """
        del self.c_qpbo
thinqpbo/src/_qpbo.pyx:32:16: Deletion of non-Python, non-C++ object
Error compiling Cython file:
        Similarly for edges.
        2. If Probe() is used with option=1 or option=2, then it is advisable to specify
        a larger value of edge_num_max (e.g. twice the number of edges in the original energy).
        """
        self.c_qpbo = new QPBO[float](node_num_max, edge_num_max)
thinqpbo/src/_qpbo.pyx:202:26: 'QPBO' is not a type identifier
Error compiling Cython file:
        Similarly for edges.
        2. If Probe() is used with option=1 or option=2, then it is advisable to specify
        a larger value of edge_num_max (e.g. twice the number of edges in the original energy).
        """
        self.c_qpbo = new QPBO[float](node_num_max, edge_num_max)
thinqpbo/src/_qpbo.pyx:202:26: new operator can only be applied to a C++ class
Error compiling Cython file:
        self.c_qpbo = new QPBO[float](node_num_max, edge_num_max)
    def __dealloc__(self):
        """Destructor
        """
        del self.c_qpbo
thinqpbo/src/_qpbo.pyx:207:16: Deletion of non-Python, non-C++ object
Error compiling Cython file:
        Similarly for edges.
        2. If Probe() is used with option=1 or option=2, then it is advisable to specify
        a larger value of edge_num_max (e.g. twice the number of edges in the original energy).
        """
        self.c_qpbo = new QPBO[double](node_num_max, edge_num_max)
thinqpbo/src/_qpbo.pyx:377:26: 'QPBO' is not a type identifier
Error compiling Cython file:
        Similarly for edges.
        2. If Probe() is used with option=1 or option=2, then it is advisable to specify
        a larger value of edge_num_max (e.g. twice the number of edges in the original energy).
        """
        self.c_qpbo = new QPBO[double](node_num_max, edge_num_max)
thinqpbo/src/_qpbo.pyx:377:26: new operator can only be applied to a C++ class
Error compiling Cython file:
        self.c_qpbo = new QPBO[double](node_num_max, edge_num_max)
    def __dealloc__(self):
        """Destructor
        """
        del self.c_qpbo
thinqpbo/src/_qpbo.pyx:382:16: Deletion of non-Python, non-C++ object
Compiling thinqpbo/src/_qpbo.pyx because it changed.
[1/1] Cythonizing thinqpbo/src/_qpbo.pyx
Traceback (most recent call last):
  File "setup.py", line 74, in <module    setup_requires=['numpy', 'Cython']
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 973, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/usr/local/lib/python3.4/dist-packages/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/lib/python3.4/distutils/command/install.py", line 357, in finalize_options
    if self.distribution.ext_modules: has extensions: non-pure
  File "setup.py", line 25, in __len__
    def __len__(self): return len(self.c_list())
  File "setup.py", line 16, in c_list
    self._list = self.callback()
  File "setup.py", line 46, in extensions
    return cythonize([maxflow_module])
  File "/usr/local/lib/python3.4/dist-packages/Cython/Build/Dependencies.py", line 1097, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Build/Dependencies.py", line 1220, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: thinqpbo/src/_qpbo.pyx

**Comment by Skielex** [comment]
I think I've found the issue. I'm missing some files in the sdist package, since they're not included in MANIFEST.in. I'll fix this asap.

**Comment by Skielex** [comment]
Should be fixed by 558ccf4199c585f1dcf75f1f19b475af77803ce5.
Released version v0.1.1 on PyPI.
