### ISSUE TITLE
apply qpbo to fuse depth map

### ISSUE THREAD

**Issue by huangyuan2020** [Skielex/thinqpbo#5]
Thank you very much for your work. I just came into contact with the qpbo algorithm recently. I tried to use the qpbo algorithm to fuse different depth maps. According to your example, I know that the entire image should be used as a graph, but it is not clear how to add nodes and set energy function in my application, can you help me?

**Comment by Skielex** [comment]
To give a you more accurate answer I probably need some more details about the problem you're trying to solve. I'm not sure how familiar you are with the literature. In case you haven't already read them, I'd recommend the original paper on [BK Maxflow](http://ieeexplore.ieee.org/document/1316848/) and [QPBO](http://ieeexplore.ieee.org/document/4204169/) by Boykov and Kolmogorov.

The `thinqpbo` package is just a simple wrapper around most of the QPBO functions. It allows you to add nodes and energy terms, and then minimize the defined energy function (solve), which will assign the optimal label (0 or 1) to each node. How you define your energy function is entirely up to you. I've also created a package called [`slgbuilder`](https://github.com/Skielex/slgbuilder) which can assist in building some common graphs, used for image segmentation. The related article can be found [here](https://openaccess.thecvf.com/content_CVPR_2020/papers/Jeppesen_Sparse_Layered_Graphs_for_Multi-Object_Segmentation_CVPR_2020_paper.pdf).
